# Generated by Django 4.1 on 2022-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
