# Generated by Django 4.1 on 2022-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_movie_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(height_field=100, upload_to=None, width_field=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shows',
            name='show_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
