# Generated by Django 4.1 on 2022-10-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_hall_city_id_hall_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='hall_id',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='shows',
            name='hall',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='booking.hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='movie',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='booking.movie'),
            preserve_default=False,
        ),
    ]
