# Generated by Django 4.1 on 2022-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_shows_hall_id_remove_shows_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='zaq12wsx', max_length=30),
            preserve_default=False,
        ),
    ]
