# Generated by Django 4.1 on 2022-10-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_shows_booking_gold_seat_shows_booking_platinum_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='gold_price',
            field=models.IntegerField(default=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='platinum_price',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
    ]
