# Generated by Django 4.1 on 2022-10-13 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0014_hall_gold_price_hall_platinum_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcket_booking',
            fields=[
                ('Tcket_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_gold_seat', models.CharField(max_length=300)),
                ('booking_platinum_seat', models.CharField(max_length=300)),
                ('booking_total_amount', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.shows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
