# Generated by Django 4.1 on 2022-10-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_tcket_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcket_booking',
            name='show',
        ),
        migrations.RemoveField(
            model_name='tcket_booking',
            name='user',
        ),
        migrations.AddField(
            model_name='tcket_booking',
            name='booking_show_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcket_booking',
            name='booking_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
