# Generated by Django 4.1 on 2022-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_tcket_booking_show_remove_tcket_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcket_booking',
            name='booking_gold_seat',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tcket_booking',
            name='booking_platinum_seat',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
